apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tucity-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - tucity.local
    secretName: tls-secret
  rules:
  - host: tucity.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: your-service-name
            port:
              number: 8080
