apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: lucvdacker/userservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT-EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-expiration
            - name: SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret-key
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
